"""Collect terminal stale-vs-refresh outcomes after controlled Task8 H4 branches.

For every selected episode this collector follows the nominal cached-H10
trajectory to macro root 10, obtains one common Action-CoT anchor, and captures
one canonical pre-H4 simulator snapshot.  Five controlled H4 prefixes are
generated by ``collect_action_cot_state_branches.make_branch_actions``.  At
each valid branch endpoint, two terminal arms start from the exact same
post-H4 snapshot:

* stale: execute cached anchor actions 4:10;
* fresh: execute actions 0:6 from one common exact endpoint Action-CoT call.

After H6, both arms perform ordinary full-H10 replanning until success or the
original LIBERO episode limit.  Replanning seeds are assigned to preregistered
absolute decision slots ``anchor_step + 10 + 10*j`` shared by both arms, so arm
timing drift cannot change policy sampling.  Common sunk anchor cost, the fresh
decision RPC, and arm-specific decision-to-terminal costs are kept separate.

One compressed NPZ per ``(episode, root, branch)`` is the resume authority.
The main episode ends after root 10; branch rollouts never alter its trajectory.
Episodes 10-29 are explicitly forbidden because they are reserved for formal
evaluation.
"""
# ruff: noqa: SLF001

from __future__ import annotations

import argparse
import json
import os
import pathlib
import time
from typing import Any, Sequence

import collect_action_cot_state_branches as state_branches
import collect_libero_plan_refresh_benefit as refresh_collector
import collect_libero_plan_validity_branches as paired_collector
import eval_libero_action_cot_pruning as libero_eval
import numpy as np
from openpi_client import websocket_client_policy as websocket_policy


SCHEMA_VERSION = 1
DEFAULT_TASK_ID = 8
DEFAULT_EPISODE_IDS = (*range(0, 10), *range(30, 50))
FIXED_ROOT_INDEX = 10
DEFAULT_BRANCHES = (
    "nominal",
    "underact",
    "overact",
    "translation_pulse",
    "gripper_fault",
)
ANCHOR_HORIZON = 4
BRANCH_HORIZON = 6
ACTION_HORIZON = 10
ACTION_DIM = 7


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--host", default="0.0.0.0")
    parser.add_argument("--port", type=int, default=8000)
    parser.add_argument("--policy-api-key", default=None)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--task-suite-name", default="libero_10")
    parser.add_argument("--task-id", type=int, default=DEFAULT_TASK_ID)
    parser.add_argument(
        "--episode-ids",
        nargs="+",
        type=int,
        default=list(DEFAULT_EPISODE_IDS),
    )
    parser.add_argument("--root-index", type=int, default=FIXED_ROOT_INDEX)
    parser.add_argument(
        "--branches",
        nargs="+",
        default=list(DEFAULT_BRANCHES),
    )
    parser.add_argument("--seed", type=int, default=7)
    parser.add_argument("--num-steps-wait", type=int, default=10)
    parser.add_argument("--resize-size", type=int, default=224)
    parser.add_argument("--action-cot-denoising-steps", type=int, default=10)
    parser.add_argument(
        "--continue-on-error",
        action=argparse.BooleanOptionalAction,
        default=True,
    )
    return parser


def _validate_args(args: argparse.Namespace) -> None:
    if args.task_id < 0:
        raise ValueError("--task-id must be non-negative.")
    if args.root_index != FIXED_ROOT_INDEX:
        raise ValueError(f"This protocol is fixed to --root-index {FIXED_ROOT_INDEX}.")
    if not args.episode_ids or any(value < 0 for value in args.episode_ids):
        raise ValueError("--episode-ids must contain non-negative IDs.")
    if len(set(args.episode_ids)) != len(args.episode_ids):
        raise ValueError("--episode-ids must not contain duplicates.")
    forbidden = sorted(value for value in args.episode_ids if 10 <= value <= 29)
    if forbidden:
        raise ValueError(
            f"Episodes 10-29 are reserved for formal evaluation and forbidden here: {forbidden}."
        )
    paired_collector._validate_args(
        argparse.Namespace(
            task_id=args.task_id,
            episode_ids=args.episode_ids,
            root_indices=[args.root_index],
            branches=args.branches,
            seed=args.seed,
            num_steps_wait=args.num_steps_wait,
            resize_size=args.resize_size,
            action_cot_denoising_steps=args.action_cot_denoising_steps,
            continuation_seed_offset=1,
        )
    )


def _pair_path(
    root_dir: pathlib.Path,
    task_id: int,
    episode_id: int,
    root_index: int,
    branch: paired_collector.BranchSpec,
) -> pathlib.Path:
    return root_dir / (
        f"task{task_id:02d}_episode{episode_id:03d}_root{root_index:03d}_"
        f"branch{branch.branch_id:02d}_{branch.name}.npz"
    )


def _logical_slot_step(anchor_decision_step: int, slot: int) -> int:
    return anchor_decision_step + ANCHOR_HORIZON + BRANCH_HORIZON + slot * ACTION_HORIZON


def _logical_seed(
    *,
    episode_id: int,
    anchor_decision_step: int,
    slot: int,
    args: argparse.Namespace,
) -> int:
    return state_branches.canonical_policy_seed(
        args.seed,
        args.task_id,
        episode_id,
        _logical_slot_step(anchor_decision_step, slot),
    )


def _terminal_reason(
    *,
    success: bool,
    done: bool,
    absolute_step: int,
    step_limit: int,
    no_progress: bool,
) -> str:
    if success:
        return "success"
    if done:
        return "environment_done"
    if absolute_step >= step_limit:
        return "step_limit"
    if no_progress:
        return "no_environment_progress"
    return "stopped"


def _run_terminal_arm(
    env: Any,
    endpoint_snapshot: state_branches.CanonicalSimulatorSnapshot,
    h6_actions: np.ndarray,
    *,
    endpoint_absolute_step: int,
    step_limit: int,
    episode_id: int,
    anchor_decision_step: int,
    task_description: str,
    args: argparse.Namespace,
    client: websocket_policy.WebsocketClientPolicy,
) -> dict[str, Any]:
    arm_started = time.perf_counter()
    observation = state_branches._restore_canonical_snapshot(env, endpoint_snapshot)
    before = refresh_collector._progress(env, observation)
    h6_started = time.perf_counter()
    h6_budget = max(0, min(BRANCH_HORIZON, step_limit - endpoint_absolute_step))
    observation, done, executed_h6 = state_branches._step_actions(
        env,
        observation,
        np.asarray(h6_actions, dtype=np.float32)[:h6_budget, :ACTION_DIM],
    )
    absolute_step = endpoint_absolute_step + len(executed_h6)
    after_h6 = refresh_collector._progress(env, observation)
    h6_elapsed_wall_ms = (time.perf_counter() - h6_started) * 1000.0

    remaining_started = time.perf_counter()
    remaining_policy_calls = 0
    remaining_policy_wall_ms = 0.0
    remaining_steps = 0
    logical_seeds: list[int] = []
    no_progress = False
    while (
        not done
        and not after_h6["success"]
        and absolute_step < step_limit
    ):
        slot = remaining_policy_calls
        policy_seed = _logical_seed(
            episode_id=episode_id,
            anchor_decision_step=anchor_decision_step,
            slot=slot,
            args=args,
        )
        policy_input = paired_collector._policy_input(observation, task_description, args)
        result = paired_collector._teacher_request(
            client,
            policy_input,
            policy_seed=policy_seed,
            args=args,
        )
        tensors = paired_collector._teacher_tensors(result)
        remaining_policy_calls += 1
        remaining_policy_wall_ms += float(result["collector_wall_ms"])
        logical_seeds.append(policy_seed)
        action_budget = min(ACTION_HORIZON, step_limit - absolute_step)
        observation, done, executed = state_branches._step_actions(
            env,
            observation,
            tensors["actions_env"][:action_budget, :ACTION_DIM],
        )
        executed_count = len(executed)
        remaining_steps += executed_count
        absolute_step += executed_count
        if executed_count == 0:
            no_progress = True
            break
        if libero_eval._env_success(env):
            done = True
            break

    terminal = refresh_collector._progress(env, observation)
    h6_executed, h6_valid = refresh_collector._padded_executed(
        executed_h6,
        BRANCH_HORIZON,
    )
    success = bool(terminal["success"])
    return {
        "before": before,
        "after_h6": after_h6,
        "terminal": terminal,
        "terminal_reason": _terminal_reason(
            success=success,
            done=done,
            absolute_step=absolute_step,
            step_limit=step_limit,
            no_progress=no_progress,
        ),
        "h6_actions": np.asarray(h6_actions, dtype=np.float32)[:BRANCH_HORIZON, :ACTION_DIM],
        "h6_executed_actions": h6_executed,
        "h6_executed_valid": h6_valid,
        "h6_executed_steps": int(np.sum(h6_valid)),
        "remaining_steps_after_h6": remaining_steps,
        "endpoint_to_terminal_steps": len(executed_h6) + remaining_steps,
        "remaining_policy_calls": remaining_policy_calls,
        "remaining_policy_wall_ms": remaining_policy_wall_ms,
        "remaining_elapsed_wall_ms": (time.perf_counter() - remaining_started) * 1000.0,
        "h6_elapsed_wall_ms": h6_elapsed_wall_ms,
        "endpoint_to_terminal_elapsed_wall_ms": (time.perf_counter() - arm_started) * 1000.0,
        "logical_policy_seeds": np.asarray(logical_seeds, dtype=np.uint32),
        "terminal_absolute_step": absolute_step,
        "success": success,
    }


def _arm_arrays(prefix: str, arm: dict[str, Any]) -> dict[str, np.ndarray]:
    return {
        f"{prefix}_h6_actions": np.asarray(arm["h6_actions"], dtype=np.float32),
        f"{prefix}_h6_executed_actions": np.asarray(
            arm["h6_executed_actions"], dtype=np.float32
        ),
        f"{prefix}_h6_executed_valid": np.asarray(
            arm["h6_executed_valid"], dtype=np.bool_
        ),
        f"{prefix}_h6_executed_steps": np.asarray(
            arm["h6_executed_steps"], dtype=np.int16
        ),
        f"{prefix}_remaining_steps_after_h6": np.asarray(
            arm["remaining_steps_after_h6"], dtype=np.int32
        ),
        f"{prefix}_endpoint_to_terminal_steps": np.asarray(
            arm["endpoint_to_terminal_steps"], dtype=np.int32
        ),
        f"{prefix}_remaining_policy_calls": np.asarray(
            arm["remaining_policy_calls"], dtype=np.int16
        ),
        f"{prefix}_remaining_policy_wall_ms": np.asarray(
            arm["remaining_policy_wall_ms"], dtype=np.float32
        ),
        f"{prefix}_remaining_elapsed_wall_ms": np.asarray(
            arm["remaining_elapsed_wall_ms"], dtype=np.float32
        ),
        f"{prefix}_h6_elapsed_wall_ms": np.asarray(
            arm["h6_elapsed_wall_ms"], dtype=np.float32
        ),
        f"{prefix}_endpoint_to_terminal_elapsed_wall_ms": np.asarray(
            arm["endpoint_to_terminal_elapsed_wall_ms"], dtype=np.float32
        ),
        f"{prefix}_logical_policy_seeds": np.asarray(
            arm["logical_policy_seeds"], dtype=np.uint32
        ),
        f"{prefix}_terminal_absolute_step": np.asarray(
            arm["terminal_absolute_step"], dtype=np.int32
        ),
        f"{prefix}_terminal_reason": np.asarray(arm["terminal_reason"]),
        f"{prefix}_terminal_success": np.asarray(arm["success"], dtype=np.bool_),
    }


def _valid_pair_arrays(
    *,
    args: argparse.Namespace,
    episode_id: int,
    initial_state_id: int,
    decision_step: int,
    step_limit: int,
    root_seed: int,
    branch: paired_collector.BranchSpec,
    anchor_input: dict[str, Any],
    endpoint_input: dict[str, Any],
    anchor_result: dict[str, Any],
    endpoint_fresh_result: dict[str, Any],
    actual_prefix: np.ndarray,
    actual_prefix_valid: np.ndarray,
    stale: dict[str, Any],
    fresh: dict[str, Any],
) -> dict[str, np.ndarray]:
    fresh_tensors = paired_collector._teacher_tensors(endpoint_fresh_result)
    arrays = paired_collector._base_arrays(
        args=args,
        episode_id=episode_id,
        initial_state_id=initial_state_id,
        root_index=args.root_index,
        decision_step=decision_step,
        root_seed=root_seed,
        continuation_seed=_logical_seed(
            episode_id=episode_id,
            anchor_decision_step=decision_step,
            slot=0,
            args=args,
        ),
        branch=branch,
        anchor_input=anchor_input,
        endpoint_input=endpoint_input,
        anchor_result=anchor_result,
        current_tensors=fresh_tensors,
        actual_prefix=actual_prefix,
        actual_prefix_valid=actual_prefix_valid,
        endpoint_done=False,
        valid=True,
        invalid_reason="",
    )
    arrays.update(
        {
            "terminal_slot0_absolute_decision_step": np.asarray(
                _logical_slot_step(decision_step, 0), dtype=np.int32
            ),
            "terminal_slot_stride_steps": np.asarray(ACTION_HORIZON, dtype=np.int16),
            "terminal_absolute_environment_step_limit": np.asarray(
                step_limit, dtype=np.int32
            ),
            "terminal_control_step_limit": np.asarray(
                libero_eval._max_steps(args.task_suite_name), dtype=np.int32
            ),
            "common_sunk_anchor_request_calls": np.asarray(1, dtype=np.int16),
            "common_sunk_anchor_request_wall_ms": np.asarray(
                anchor_result["collector_wall_ms"], dtype=np.float32
            ),
            "fresh_decision_refresh_request_calls": np.asarray(1, dtype=np.int16),
            "fresh_decision_refresh_request_wall_ms": np.asarray(
                endpoint_fresh_result["collector_wall_ms"], dtype=np.float32
            ),
        }
    )
    arrays.update(_arm_arrays("stale", stale))
    arrays.update(_arm_arrays("fresh", fresh))
    arrays.update(refresh_collector._progress_arrays("before", stale["before"]))
    arrays.update(refresh_collector._progress_arrays("stale_h6", stale["after_h6"]))
    arrays.update(refresh_collector._progress_arrays("fresh_h6", fresh["after_h6"]))
    arrays.update(
        refresh_collector._progress_arrays("stale_terminal", stale["terminal"])
    )
    arrays.update(
        refresh_collector._progress_arrays("fresh_terminal", fresh["terminal"])
    )
    arrays.update(
        refresh_collector._advantage_arrays(
            "h6",
            stale["after_h6"],
            fresh["after_h6"],
        )
    )
    arrays.update(
        refresh_collector._advantage_arrays(
            "terminal",
            stale["terminal"],
            fresh["terminal"],
        )
    )
    arrays.update(
        {
            "terminal_success_difference": np.asarray(
                int(fresh["success"]) - int(stale["success"]), dtype=np.int8
            ),
            "terminal_privileged_progress_difference": np.asarray(
                fresh["terminal"]["normalized_score"]
                - stale["terminal"]["normalized_score"],
                dtype=np.float32,
            ),
            "fresh_minus_stale_remaining_steps_after_h6": np.asarray(
                fresh["remaining_steps_after_h6"] - stale["remaining_steps_after_h6"],
                dtype=np.int32,
            ),
            "fresh_minus_stale_remaining_policy_calls": np.asarray(
                fresh["remaining_policy_calls"] - stale["remaining_policy_calls"],
                dtype=np.int16,
            ),
            "fresh_minus_stale_remaining_policy_wall_ms": np.asarray(
                fresh["remaining_policy_wall_ms"] - stale["remaining_policy_wall_ms"],
                dtype=np.float32,
            ),
            "fresh_minus_stale_remaining_elapsed_wall_ms": np.asarray(
                fresh["remaining_elapsed_wall_ms"] - stale["remaining_elapsed_wall_ms"],
                dtype=np.float32,
            ),
            "stale_decision_to_terminal_policy_calls": np.asarray(
                stale["remaining_policy_calls"], dtype=np.int16
            ),
            "fresh_decision_to_terminal_policy_calls": np.asarray(
                1 + fresh["remaining_policy_calls"], dtype=np.int16
            ),
            "stale_decision_to_terminal_policy_wall_ms": np.asarray(
                stale["remaining_policy_wall_ms"], dtype=np.float32
            ),
            "fresh_decision_to_terminal_policy_wall_ms": np.asarray(
                float(endpoint_fresh_result["collector_wall_ms"])
                + fresh["remaining_policy_wall_ms"],
                dtype=np.float32,
            ),
            "physical_collector_pair_policy_calls": np.asarray(
                2 + stale["remaining_policy_calls"] + fresh["remaining_policy_calls"],
                dtype=np.int16,
            ),
            "physical_collector_pair_policy_wall_ms": np.asarray(
                float(anchor_result["collector_wall_ms"])
                + float(endpoint_fresh_result["collector_wall_ms"])
                + stale["remaining_policy_wall_ms"]
                + fresh["remaining_policy_wall_ms"],
                dtype=np.float32,
            ),
        }
    )
    return arrays


def _invalid_pair_arrays(
    *,
    args: argparse.Namespace,
    episode_id: int,
    initial_state_id: int,
    decision_step: int,
    step_limit: int,
    root_seed: int,
    branch: paired_collector.BranchSpec,
    anchor_input: dict[str, Any],
    endpoint_input: dict[str, Any],
    anchor_result: dict[str, Any],
    actual_prefix: np.ndarray,
    actual_prefix_valid: np.ndarray,
    endpoint_done: bool,
    endpoint_progress: dict[str, Any],
    invalid_reason: str,
) -> dict[str, np.ndarray]:
    arrays = paired_collector._invalid_arrays(
        args=args,
        episode_id=episode_id,
        initial_state_id=initial_state_id,
        root_index=args.root_index,
        decision_step=decision_step,
        root_seed=root_seed,
        continuation_seed=_logical_seed(
            episode_id=episode_id,
            anchor_decision_step=decision_step,
            slot=0,
            args=args,
        ),
        branch=branch,
        anchor_input=anchor_input,
        endpoint_input=endpoint_input,
        anchor_result=anchor_result,
        actual_prefix=actual_prefix,
        actual_prefix_valid=actual_prefix_valid,
        endpoint_done=endpoint_done,
        invalid_reason=invalid_reason,
        endpoint_progress=endpoint_progress,
    )
    empty_arm = {
        "h6_actions": np.zeros((BRANCH_HORIZON, ACTION_DIM), dtype=np.float32),
        "h6_executed_actions": np.zeros((BRANCH_HORIZON, ACTION_DIM), dtype=np.float32),
        "h6_executed_valid": np.zeros((BRANCH_HORIZON,), dtype=np.bool_),
        "h6_executed_steps": 0,
        "remaining_steps_after_h6": 0,
        "endpoint_to_terminal_steps": 0,
        "remaining_policy_calls": 0,
        "remaining_policy_wall_ms": 0.0,
        "remaining_elapsed_wall_ms": 0.0,
        "h6_elapsed_wall_ms": 0.0,
        "endpoint_to_terminal_elapsed_wall_ms": 0.0,
        "logical_policy_seeds": np.zeros((0,), dtype=np.uint32),
        "terminal_absolute_step": decision_step + int(np.sum(actual_prefix_valid)),
        "terminal_reason": invalid_reason,
        "success": bool(endpoint_progress["success"]),
    }
    arrays.update(_arm_arrays("stale", empty_arm))
    arrays.update(_arm_arrays("fresh", empty_arm))
    arrays.update(
        {
            "terminal_slot0_absolute_decision_step": np.asarray(
                _logical_slot_step(decision_step, 0), dtype=np.int32
            ),
            "terminal_slot_stride_steps": np.asarray(ACTION_HORIZON, dtype=np.int16),
            "terminal_absolute_environment_step_limit": np.asarray(
                step_limit, dtype=np.int32
            ),
            "terminal_control_step_limit": np.asarray(
                libero_eval._max_steps(args.task_suite_name), dtype=np.int32
            ),
            "common_sunk_anchor_request_calls": np.asarray(1, dtype=np.int16),
            "common_sunk_anchor_request_wall_ms": np.asarray(
                anchor_result["collector_wall_ms"], dtype=np.float32
            ),
            "fresh_decision_refresh_request_calls": np.asarray(0, dtype=np.int16),
            "fresh_decision_refresh_request_wall_ms": np.asarray(0.0, dtype=np.float32),
            "terminal_success_difference": np.asarray(0, dtype=np.int8),
            "terminal_privileged_progress_difference": np.asarray(0.0, dtype=np.float32),
            "fresh_minus_stale_remaining_steps_after_h6": np.asarray(0, dtype=np.int32),
            "fresh_minus_stale_remaining_policy_calls": np.asarray(0, dtype=np.int16),
            "fresh_minus_stale_remaining_policy_wall_ms": np.asarray(0.0, dtype=np.float32),
            "fresh_minus_stale_remaining_elapsed_wall_ms": np.asarray(0.0, dtype=np.float32),
            "stale_decision_to_terminal_policy_calls": np.asarray(0, dtype=np.int16),
            "fresh_decision_to_terminal_policy_calls": np.asarray(0, dtype=np.int16),
            "stale_decision_to_terminal_policy_wall_ms": np.asarray(0.0, dtype=np.float32),
            "fresh_decision_to_terminal_policy_wall_ms": np.asarray(0.0, dtype=np.float32),
            "physical_collector_pair_policy_calls": np.asarray(1, dtype=np.int16),
            "physical_collector_pair_policy_wall_ms": np.asarray(
                anchor_result["collector_wall_ms"], dtype=np.float32
            ),
        }
    )
    arrays.update(refresh_collector._progress_arrays("stale_terminal", endpoint_progress))
    arrays.update(refresh_collector._progress_arrays("fresh_terminal", endpoint_progress))
    arrays.update(
        refresh_collector._advantage_arrays(
            "terminal",
            endpoint_progress,
            endpoint_progress,
        )
    )
    return arrays


def _scalar(arrays: Any, name: str) -> Any:
    return np.asarray(arrays[name]).reshape(()).item()


def _scalar_or_default(arrays: Any, name: str, default: Any) -> Any:
    if name not in arrays:
        return default
    return _scalar(arrays, name)


def _index_row(path: pathlib.Path, output_dir: pathlib.Path) -> dict[str, Any]:
    with np.load(path, allow_pickle=False) as arrays:
        return {
            "schema_version": int(_scalar(arrays, "schema_version")),
            "valid": bool(_scalar(arrays, "valid")),
            "invalid_reason": str(_scalar(arrays, "invalid_reason")),
            "task_id": int(_scalar(arrays, "task_id")),
            "episode_id": int(_scalar(arrays, "episode_id")),
            "initial_state_id": int(_scalar(arrays, "initial_state_id")),
            "root_index": int(_scalar(arrays, "root_index")),
            "branch_id": int(_scalar(arrays, "branch_id")),
            "branch_name": str(_scalar(arrays, "branch_name")),
            "branch_canonical_name": str(_scalar(arrays, "branch_canonical_name")),
            "branch_strength": float(_scalar(arrays, "branch_strength")),
            "terminal_success_difference": int(
                _scalar(arrays, "terminal_success_difference")
            ),
            "terminal_privileged_progress_difference": float(
                _scalar(arrays, "terminal_privileged_progress_difference")
            ),
            "fresh_minus_stale_h6_normalized_score": float(
                _scalar_or_default(
                    arrays,
                    "fresh_minus_stale_h6_normalized_score",
                    float("nan"),
                )
            ),
            "fresh_minus_stale_terminal_normalized_score": float(
                _scalar(arrays, "fresh_minus_stale_terminal_normalized_score")
            ),
            "fresh_minus_stale_terminal_satisfied_count": int(
                _scalar(arrays, "fresh_minus_stale_terminal_satisfied_count")
            ),
            "stale_remaining_policy_calls": int(
                _scalar(arrays, "stale_remaining_policy_calls")
            ),
            "fresh_remaining_policy_calls": int(
                _scalar(arrays, "fresh_remaining_policy_calls")
            ),
            "stale_remaining_policy_wall_ms": float(
                _scalar(arrays, "stale_remaining_policy_wall_ms")
            ),
            "fresh_remaining_policy_wall_ms": float(
                _scalar(arrays, "fresh_remaining_policy_wall_ms")
            ),
            "stale_decision_to_terminal_policy_calls": int(
                _scalar(arrays, "stale_decision_to_terminal_policy_calls")
            ),
            "fresh_decision_to_terminal_policy_calls": int(
                _scalar(arrays, "fresh_decision_to_terminal_policy_calls")
            ),
            "stale_decision_to_terminal_policy_wall_ms": float(
                _scalar(arrays, "stale_decision_to_terminal_policy_wall_ms")
            ),
            "fresh_decision_to_terminal_policy_wall_ms": float(
                _scalar(arrays, "fresh_decision_to_terminal_policy_wall_ms")
            ),
            "npz_file": str(path.relative_to(output_dir)),
        }


def _collect_pair(
    env: Any,
    pre_h4_snapshot: state_branches.CanonicalSimulatorSnapshot,
    *,
    branch: paired_collector.BranchSpec,
    task_description: str,
    episode_id: int,
    initial_state_id: int,
    decision_step: int,
    step_limit: int,
    root_seed: int,
    anchor_input: dict[str, Any],
    anchor_result: dict[str, Any],
    anchor_tensors: dict[str, np.ndarray],
    args: argparse.Namespace,
    client: websocket_policy.WebsocketClientPolicy,
    output_path: pathlib.Path,
) -> dict[str, Any]:
    observation = state_branches._restore_canonical_snapshot(env, pre_h4_snapshot)
    observation, done, executed = state_branches._step_actions(
        env,
        observation,
        branch.actions,
    )
    actual_prefix, actual_prefix_valid = refresh_collector._padded_executed(
        executed,
        ANCHOR_HORIZON,
    )
    endpoint_input = paired_collector._policy_input(observation, task_description, args)
    if done or libero_eval._env_success(env) or len(executed) < ANCHOR_HORIZON:
        reason = (
            "terminal_or_success_during_prefix"
            if done or libero_eval._env_success(env)
            else "short_prefix_execution"
        )
        arrays = _invalid_pair_arrays(
            args=args,
            episode_id=episode_id,
            initial_state_id=initial_state_id,
            decision_step=decision_step,
            step_limit=step_limit,
            root_seed=root_seed,
            branch=branch,
            anchor_input=anchor_input,
            endpoint_input=endpoint_input,
            anchor_result=anchor_result,
            actual_prefix=actual_prefix,
            actual_prefix_valid=actual_prefix_valid,
            endpoint_done=bool(done or libero_eval._env_success(env)),
            endpoint_progress=refresh_collector._progress(env, observation),
            invalid_reason=reason,
        )
        paired_collector._write_npz_atomic(output_path, arrays)
        return _index_row(output_path, output_path.parent.parent)

    endpoint_snapshot = state_branches._capture_canonical_snapshot(env)
    endpoint_fresh_result = paired_collector._teacher_request(
        client,
        endpoint_input,
        policy_seed=root_seed,
        args=args,
    )
    fresh_tensors = paired_collector._teacher_tensors(endpoint_fresh_result)
    stale_h6 = np.asarray(
        anchor_tensors["actions_env"][
            ANCHOR_HORIZON : ANCHOR_HORIZON + BRANCH_HORIZON,
            :ACTION_DIM,
        ],
        dtype=np.float32,
    )
    fresh_h6 = np.asarray(
        fresh_tensors["actions_env"][:BRANCH_HORIZON, :ACTION_DIM],
        dtype=np.float32,
    )
    endpoint_absolute_step = decision_step + ANCHOR_HORIZON
    try:
        stale = _run_terminal_arm(
            env,
            endpoint_snapshot,
            stale_h6,
            endpoint_absolute_step=endpoint_absolute_step,
            step_limit=step_limit,
            episode_id=episode_id,
            anchor_decision_step=decision_step,
            task_description=task_description,
            args=args,
            client=client,
        )
        fresh = _run_terminal_arm(
            env,
            endpoint_snapshot,
            fresh_h6,
            endpoint_absolute_step=endpoint_absolute_step,
            step_limit=step_limit,
            episode_id=episode_id,
            anchor_decision_step=decision_step,
            task_description=task_description,
            args=args,
            client=client,
        )
        arrays = _valid_pair_arrays(
            args=args,
            episode_id=episode_id,
            initial_state_id=initial_state_id,
            decision_step=decision_step,
            step_limit=step_limit,
            root_seed=root_seed,
            branch=branch,
            anchor_input=anchor_input,
            endpoint_input=endpoint_input,
            anchor_result=anchor_result,
            endpoint_fresh_result=endpoint_fresh_result,
            actual_prefix=actual_prefix,
            actual_prefix_valid=actual_prefix_valid,
            stale=stale,
            fresh=fresh,
        )
        paired_collector._write_npz_atomic(output_path, arrays)
        return _index_row(output_path, output_path.parent.parent)
    finally:
        state_branches._restore_canonical_snapshot(env, pre_h4_snapshot)


def _protocol_signature(args: argparse.Namespace) -> dict[str, Any]:
    return {
        "task_id": args.task_id,
        "episode_ids": list(args.episode_ids),
        "root_index": args.root_index,
        "branches": [item[1] for item in paired_collector._protocol_branches(args)],
        "canonical_branches": [
            item[2] for item in paired_collector._protocol_branches(args)
        ],
        "seed": args.seed,
        "action_cot_denoising_steps": args.action_cot_denoising_steps,
        "terminal_slot0_offset_steps": ANCHOR_HORIZON + BRANCH_HORIZON,
        "terminal_slot_stride_steps": ACTION_HORIZON,
    }


def _episode_already_complete(
    rows: Sequence[dict[str, Any]], episode_id: int, args: argparse.Namespace
) -> bool:
    signature = _protocol_signature(args)
    for row in reversed(rows):
        if int(row.get("episode_id", -1)) != episode_id:
            continue
        return bool(row.get("complete", False)) and row.get("protocol") == signature
    return False


def _run_episode(
    *,
    task: Any,
    initial_state: Any,
    initial_state_id: int,
    episode_id: int,
    indexed_keys: set[tuple[int, int, int, int]],
    args: argparse.Namespace,
    client: websocket_policy.WebsocketClientPolicy,
    output_dir: pathlib.Path,
    root_dir: pathlib.Path,
    index_file: Any,
) -> dict[str, Any]:
    env, task_description = libero_eval._get_libero_env(
        task,
        libero_eval.LIBERO_ENV_RESOLUTION,
        args.seed,
    )
    started = time.monotonic()
    new_files = 0
    resumed_files = 0
    repaired_rows = 0
    failed = 0
    invalid = 0
    reach_policy_calls = 0
    reach_policy_wall_ms = 0.0
    try:
        env.reset()
        observation = env.set_init_state(initial_state)
        step = 0
        done = False
        for _ in range(args.num_steps_wait):
            observation, _, done, _ = env.step(libero_eval.LIBERO_DUMMY_ACTION)
            step += 1
            if done:
                break

        environment_horizon = libero_eval._env_horizon(env)
        step_limit = libero_eval._max_steps(args.task_suite_name) + args.num_steps_wait
        if environment_horizon is not None:
            step_limit = min(step_limit, environment_horizon)

        root_index = 0
        termination_reason = ""
        while not done and step < step_limit and root_index <= args.root_index:
            decision_step = step
            root_seed = state_branches.canonical_policy_seed(
                args.seed,
                args.task_id,
                episode_id,
                decision_step,
            )
            anchor_input = paired_collector._policy_input(
                observation,
                task_description,
                args,
            )
            anchor_result = paired_collector._teacher_request(
                client,
                anchor_input,
                policy_seed=root_seed,
                args=args,
            )
            anchor_tensors = paired_collector._teacher_tensors(anchor_result)
            reach_policy_calls += 1
            reach_policy_wall_ms += float(anchor_result["collector_wall_ms"])

            if root_index < args.root_index:
                observation, done, executed = state_branches._step_actions(
                    env,
                    observation,
                    anchor_tensors["actions_env"][:ACTION_HORIZON, :ACTION_DIM],
                )
                actual_steps = len(executed)
                step += actual_steps
                root_index += 1
                if actual_steps == 0:
                    termination_reason = "no_environment_progress"
                    break
                continue

            pre_h4_snapshot = state_branches._capture_canonical_snapshot(env)
            for branch in paired_collector._branch_specs(
                anchor_tensors["actions_env"], args
            ):
                output_path = _pair_path(
                    root_dir,
                    args.task_id,
                    episode_id,
                    root_index,
                    branch,
                )
                key = (args.task_id, episode_id, root_index, branch.branch_id)
                if output_path.exists():
                    if key not in indexed_keys:
                        row = _index_row(output_path, output_dir)
                        refresh_collector._append_jsonl(index_file, row)
                        indexed_keys.add(key)
                        repaired_rows += 1
                    resumed_files += 1
                    continue
                try:
                    row = _collect_pair(
                        env,
                        pre_h4_snapshot,
                        branch=branch,
                        task_description=task_description,
                        episode_id=episode_id,
                        initial_state_id=initial_state_id,
                        decision_step=decision_step,
                        step_limit=step_limit,
                        root_seed=root_seed,
                        anchor_input=anchor_input,
                        anchor_result=anchor_result,
                        anchor_tensors=anchor_tensors,
                        args=args,
                        client=client,
                        output_path=output_path,
                    )
                    refresh_collector._append_jsonl(index_file, row)
                    indexed_keys.add(key)
                    new_files += 1
                    invalid += int(not row["valid"])
                    print(
                        json.dumps(
                            {
                                "task_id": args.task_id,
                                "episode_id": episode_id,
                                "root_index": root_index,
                                "branch": branch.name,
                                "valid": row["valid"],
                                "terminal_success_difference": row[
                                    "terminal_success_difference"
                                ],
                                "terminal_progress_difference": row[
                                    "terminal_privileged_progress_difference"
                                ],
                                "stale_remaining_calls": row[
                                    "stale_remaining_policy_calls"
                                ],
                                "fresh_remaining_calls": row[
                                    "fresh_remaining_policy_calls"
                                ],
                                "npz_file": row["npz_file"],
                            },
                            sort_keys=True,
                        ),
                        flush=True,
                    )
                except Exception as exc:
                    failed += 1
                    print(
                        json.dumps(
                            {
                                "task_id": args.task_id,
                                "episode_id": episode_id,
                                "root_index": root_index,
                                "branch": branch.name,
                                "error": f"{type(exc).__name__}: {exc}",
                            },
                            sort_keys=True,
                        ),
                        flush=True,
                    )
                    if not args.continue_on_error:
                        raise
                finally:
                    observation = state_branches._restore_canonical_snapshot(
                        env,
                        pre_h4_snapshot,
                    )
            root_index += 1
            termination_reason = "target_root_complete"
            break

        success_before_target = bool(done or libero_eval._env_success(env))
        if success_before_target and root_index <= args.root_index:
            termination_reason = "success_before_target_root"
        elif not termination_reason and step >= step_limit:
            termination_reason = "step_limit_before_target_root"
        return {
            "schema_version": SCHEMA_VERSION,
            "task_suite_name": args.task_suite_name,
            "task_id": args.task_id,
            "task_description": str(task_description),
            "episode_id": episode_id,
            "initial_state_id": initial_state_id,
            "termination_reason": termination_reason,
            "environment_steps_to_target": step,
            "control_steps_to_target": max(0, step - args.num_steps_wait),
            "roots_visited": root_index,
            "reach_policy_calls_including_target_anchor": reach_policy_calls,
            "reach_policy_wall_ms_including_target_anchor": reach_policy_wall_ms,
            "new_pair_files": new_files,
            "resumed_pair_files": resumed_files,
            "repaired_index_rows": repaired_rows,
            "invalid_pair_files": invalid,
            "failed_pairs": failed,
            "complete": failed == 0,
            "protocol": _protocol_signature(args),
            "elapsed_seconds": time.monotonic() - started,
        }
    finally:
        libero_eval._safe_close_env(env)


def _summary(
    args: argparse.Namespace,
    pair_rows: Sequence[dict[str, Any]],
    episode_rows: Sequence[dict[str, Any]],
) -> dict[str, Any]:
    episode_set = set(args.episode_ids)
    branch_ids = {item[0] for item in paired_collector._protocol_branches(args)}
    selected = [
        row
        for row in pair_rows
        if int(row.get("task_id", -1)) == args.task_id
        and int(row.get("episode_id", -1)) in episode_set
        and int(row.get("root_index", -1)) == args.root_index
        and int(row.get("branch_id", -1)) in branch_ids
    ]
    selected = list(
        {
            (
                int(row["task_id"]),
                int(row["episode_id"]),
                int(row["root_index"]),
                int(row["branch_id"]),
            ): row
            for row in selected
        }.values()
    )
    complete_episodes = {
        int(row["episode_id"])
        for row in episode_rows
        if int(row.get("task_id", -1)) == args.task_id
        and int(row.get("episode_id", -1)) in episode_set
        and bool(row.get("complete", False))
        and row.get("protocol") == _protocol_signature(args)
    }
    by_branch = {}
    for branch_id, display_name, _ in paired_collector._protocol_branches(args):
        rows = [row for row in selected if int(row["branch_id"]) == branch_id]
        valid = [row for row in rows if bool(row["valid"])]
        success_delta = [int(row["terminal_success_difference"]) for row in valid]
        progress_delta = [
            float(row["terminal_privileged_progress_difference"]) for row in valid
        ]
        by_branch[display_name] = {
            "files": len(rows),
            "valid": len(valid),
            "invalid": len(rows) - len(valid),
            "fresh_terminal_rescues": int(sum(value > 0 for value in success_delta)),
            "fresh_terminal_regressions": int(sum(value < 0 for value in success_delta)),
            "terminal_success_ties": int(sum(value == 0 for value in success_delta)),
            "mean_terminal_progress_difference": (
                float(np.mean(progress_delta)) if progress_delta else None
            ),
            "terminal_progress_wins": int(sum(value > 0 for value in progress_delta)),
            "terminal_progress_losses": int(sum(value < 0 for value in progress_delta)),
            "mean_fresh_minus_stale_decision_to_terminal_calls": (
                float(
                    np.mean(
                        [
                            int(row["fresh_decision_to_terminal_policy_calls"])
                            - int(row["stale_decision_to_terminal_policy_calls"])
                            for row in valid
                        ]
                    )
                )
                if valid
                else None
            ),
        }
    return {
        "schema_version": SCHEMA_VERSION,
        "status": (
            "complete" if len(complete_episodes) == len(args.episode_ids) else "running"
        ),
        "protocol": {
            **_protocol_signature(args),
            "task_suite_name": args.task_suite_name,
            "trajectory_to_target": "nominal cached H10",
            "target_root": FIXED_ROOT_INDEX,
            "pair_start": "same canonical post-branch-H4 snapshot",
            "arms": "cached stale H6 versus endpoint exact fresh H6",
            "terminal_continuation": "ordinary full-H10 replanning",
            "seed_protocol": (
                "canonical_policy_seed(seed,task,episode,anchor_decision_step+10+10*j)"
            ),
            "cost_accounting": (
                "common sunk anchor is separate; fresh decision cost includes endpoint refresh; "
                "physical two-arm collector RPC is diagnostic and not deployment cost"
            ),
            "formal_episode_ids_forbidden": list(range(10, 30)),
            "resume_authority": "one compressed NPZ per episode/root/branch",
        },
        "completed_episodes": len(complete_episodes),
        "requested_episodes": len(args.episode_ids),
        "pair_files": len(selected),
        "expected_pair_files_if_target_reachable": len(args.episode_ids) * len(args.branches),
        "by_branch": by_branch,
        "note": (
            "Development labels only. Formal episodes 10-29 are not read or written by this collector."
        ),
    }


def main(args: argparse.Namespace) -> None:
    _validate_args(args)
    output_dir = pathlib.Path(args.output_dir)
    root_dir = output_dir / "pairs"
    output_dir.mkdir(parents=True, exist_ok=True)
    root_dir.mkdir(parents=True, exist_ok=True)
    index_path = output_dir / "pairs.jsonl"
    episodes_path = output_dir / "episodes.jsonl"
    summary_path = output_dir / "summary.json"

    pair_rows = refresh_collector._read_jsonl(index_path)
    episode_rows = refresh_collector._read_jsonl(episodes_path)
    indexed_keys = {
        (
            int(row["task_id"]),
            int(row["episode_id"]),
            int(row["root_index"]),
            int(row["branch_id"]),
        )
        for row in pair_rows
        if all(
            name in row
            for name in ("task_id", "episode_id", "root_index", "branch_id")
        )
    }

    client = websocket_policy.WebsocketClientPolicy(
        args.host,
        args.port,
        api_key=args.policy_api_key,
        ping_interval=None,
        ping_timeout=None,
    )
    suite = libero_eval.benchmark.get_benchmark_dict()[args.task_suite_name]()
    if args.task_id >= suite.n_tasks:
        raise ValueError(f"Task ID {args.task_id} is outside suite size {suite.n_tasks}.")
    task = suite.get_task(args.task_id)
    initial_states = suite.get_task_init_states(args.task_id)

    with index_path.open("a", encoding="utf-8") as index_file, episodes_path.open(
        "a",
        encoding="utf-8",
    ) as episodes_file:
        for episode_id in args.episode_ids:
            if _episode_already_complete(episode_rows, episode_id, args):
                continue
            initial_state_id = episode_id % len(initial_states)
            row = _run_episode(
                task=task,
                initial_state=initial_states[initial_state_id],
                initial_state_id=initial_state_id,
                episode_id=episode_id,
                indexed_keys=indexed_keys,
                args=args,
                client=client,
                output_dir=output_dir,
                root_dir=root_dir,
                index_file=index_file,
            )
            refresh_collector._append_jsonl(episodes_file, row)
            episode_rows.append(row)
            pair_rows = refresh_collector._read_jsonl(index_path)
            summary = _summary(args, pair_rows, episode_rows)
            summary_path.write_text(
                json.dumps(summary, indent=2, sort_keys=True, allow_nan=False) + "\n",
                encoding="utf-8",
            )
            print(json.dumps(row, sort_keys=True, allow_nan=False), flush=True)

    pair_rows = refresh_collector._read_jsonl(index_path)
    episode_rows = refresh_collector._read_jsonl(episodes_path)
    summary = _summary(args, pair_rows, episode_rows)
    summary_path.write_text(
        json.dumps(summary, indent=2, sort_keys=True, allow_nan=False) + "\n",
        encoding="utf-8",
    )
    print(json.dumps(summary, sort_keys=True, allow_nan=False), flush=True)


if __name__ == "__main__":
    main(build_parser().parse_args())
